# Generated by Django 4.1.5 on 2023-01-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
            ],
        ),
    ]
