# Generated by Django 4.1.5 on 2023-01-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(null='True', upload_to='profile_pics'),
            preserve_default='True',
        ),
    ]
